spring:
    application:
        name: gateway
    config:
        import: configserver:http://localhost:8000
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/microservices-realm