spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8400
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8300
          predicates:
            - Path=/api/v1/schools/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8100
management:
  tracing:
    sampling:
      probability: 1.0