spring:
  application:
    name: school
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      file: school/compose.yaml
server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0